export const pseudocode = {
    'bubble-sort': [
        'function bubbleSort(arr):',
        '  n = length(arr)',
        '  for i = 0 to n - 2:',
        '    for j = 0 to n - i - 2:',
        '      if arr[j] > arr[j + 1]:',
        '        swap(arr[j], arr[j + 1])',
        '  return arr'
    ],
    'selection-sort': [
        'function selectionSort(arr):',
        '  n = length(arr)',
        '  for i = 0 to n - 2:',
        '    minIndex = i',
        '    for j = i + 1 to n - 1:',
        '      if arr[j] < arr[minIndex]:',
        '        minIndex = j',
        '    if minIndex != i:',
        '      swap(arr[i], arr[minIndex])',
        '  return arr'
    ],
    'insertion-sort': [
        'function insertionSort(arr):',
        '  n = length(arr)',
        '  for i = 1 to n - 1:',
        '    key = arr[i]',
        '    j = i - 1',
        '    while j >= 0 and arr[j] > key:',
        '      arr[j + 1] = arr[j]',
        '      j = j - 1',
        '    arr[j + 1] = key',
        '  return arr'
    ],
    'merge-sort': [
        'function mergeSort(arr, left, right):',
        '  if left < right:',
        '    mid = (left + right) / 2',
        '    mergeSort(arr, left, mid)',
        '    mergeSort(arr, mid + 1, right)',
        '    merge(arr, left, mid, right)',
        '',
        'function merge(arr, left, mid, right):',
        '  // Create temp arrays',
        '  // Copy data to temp arrays',
        '  // Merge temp arrays back',
        '  i = 0, j = 0, k = left',
        '  while i < n1 and j < n2:',
        '    if leftArr[i] <= rightArr[j]:',
        '      arr[k] = leftArr[i], i++',
        '    else:',
        '      arr[k] = rightArr[j], j++',
        '    k++',
        '  // Copy remaining elements'
    ],
    'quick-sort': [
        'function quickSort(arr, low, high):',
        '  if low < high:',
        '    pivotIndex = partition(arr, low, high)',
        '    quickSort(arr, low, pivotIndex - 1)',
        '    quickSort(arr, pivotIndex + 1, high)',
        '',
        'function partition(arr, low, high):',
        '  pivot = arr[high]',
        '  i = low - 1',
        '  for j = low to high - 1:',
        '    if arr[j] < pivot:',
        '      i++, swap(arr[i], arr[j])',
        '  swap(arr[i + 1], arr[high])',
        '  return i + 1'
    ],
    'heap-sort': [
        'function heapSort(arr):',
        '  n = length(arr)',
        '  // Build max heap',
        '  for i = n/2 - 1 down to 0:',
        '    heapify(arr, n, i)',
        '  // Extract elements from heap',
        '  for i = n - 1 down to 1:',
        '    swap(arr[0], arr[i])',
        '    heapify(arr, i, 0)',
        '',
        'function heapify(arr, n, i):',
        '  largest = i',
        '  left = 2*i + 1',
        '  right = 2*i + 2',
        '  if left < n and arr[left] > arr[largest]:',
        '    largest = left',
        '  if right < n and arr[right] > arr[largest]:',
        '    largest = right',
        '  if largest != i:',
        '    swap(arr[i], arr[largest])',
        '    heapify(arr, n, largest)'
    ],
    'linear-search': [
        'function linearSearch(arr, target):',
        '  for i = 0 to length(arr) - 1:',
        '    if arr[i] == target:',
        '      return i',
        '  return -1'
    ],
    'binary-search': [
        'function binarySearch(arr, target):',
        '  left = 0',
        '  right = length(arr) - 1',
        '  while left <= right:',
        '    mid = (left + right) / 2',
        '    if arr[mid] == target:',
        '      return mid',
        '    else if arr[mid] < target:',
        '      left = mid + 1',
        '    else:',
        '      right = mid - 1',
        '  return -1'
    ]
};